# Config for local Jekyll tests
theme: just-the-docs

# ==================================================
# == everything below is the same as _config.yaml ==
# ==================================================

title: AI in Production Guide
description: >-
  This article serves as a comprehensive guide and a centralized resource for
  technical professionals venturing into the world of artificial intelligence
  with Azure. It aims to demystify the process of AI project development and
  provide a smooth transition of AI workloads into a production environment.
baseurl: "/ai-in-production-guide"
url: ""

favicon_ico: "/media/favicon.png"
enable_copy_code_button: true
heading_anchors: true

callouts:
  highlight:
    color: yellow
  console:
    color: green
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

aux_links:
  "GitHub":
    - "https://github.com/soferreira/AI-in-Production-Guide"

back_to_top: false
back_to_top_text: "Back to top"

gh_edit_link: true
gh_edit_link_text: "Edit this page"
gh_edit_repository: "https://github.com/soferreira/AI-in-Production-Guide"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

search_enabled: true
search:
  # Split pages into sections that can be searched individually # Supports 1 - 6, default: 6
  heading_level: 6
  # Maximum amount of previews per search result # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview # Default: 5
  preview_words_before: 6
  # Maximum amount of words to display after a matched word in the preview # Default: 10
  preview_words_after: 10
  # Set the search token separator # Default: /[\s\-/]+/ # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results # Supports true (default) or false
  rel_url: false
  # Enable or disable the search button that appears in the bottom right corner of every page # Supports true or false (default)
  button: true

mermaid:
  # See https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.6.1"
